sudo: false

language: perl

perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
  - '5.26'
  - dev
  - blead

matrix:
  allow_failures:
    - perl: blead

env:
  global:
    - RELEASE_TESTING=1

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

notifications:
  email: false
